codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
  ignore:
  - testsrc/.*
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false

Bold values are default.

codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"

    hipchat:
      default:
        url: null
        notify: no
        threshold: null
        branches: null
        card: yes
        only_pulls: null
        message: null

    gitter:
      default:
        url: null
        threshold: null
        branches: null
        message: null

    webhook:
      default:
        url: null
        threshold: null
        branches: null
        only_pulls: null

    irc:
      default:
        server: null
        channel: null
        branches: null
        threshold: null
        message: null

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default

Learn more about why we use a yaml file for team and project settings.

Please click on a yaml setting to review documentation.

Have a question? Feel free to ask our Support Team
© 2016 Codecov Terms Privacy Security Changelog
Pricing Support Docs Enterprise
